---
exclude_paths:
  - bin
  - spec

detectors:
  IrresponsibleModule:
    enabled: false
  UtilityFunction:
    exclude:
      - "Lexdrill::CLI#run_start"
      - "Lexdrill::CLI#run_stop"
      - "Lexdrill::CLI#clear_beat"
      - "Lexdrill::CLI#colored_line"
      - "Lexdrill::CLI#set_rand_beat"
      - "Lexdrill::CLI#jump_to"
      - "Lexdrill::CLI#push_rows"
      - "Lexdrill::CLI#current_token"
      - "Lexdrill::CLI#current_marker"
  TooManyMethods:
    exclude:
      - "Lexdrill::CLI"
  RepeatedConditional:
    exclude:
      - "Lexdrill::CLI"
  ControlParameter:
    exclude:
      - "Lexdrill::CLI#current_marker"
  NilCheck:
    exclude:
      - "Lexdrill::CLI#run_wb"
      - "Lexdrill::CLI#run_sh"
  TooManyStatements:
    exclude:
      - "Lexdrill::Beat#self.locate"
      - "Lexdrill::CLI#run_add"
      - "Lexdrill::CLI#run_list"
      - "Lexdrill::CLI#run_stats"
      - "Lexdrill::CLI#run_go"
      - "Lexdrill::CLI#run_push"
      - "Lexdrill::CLI#run_pull"
      - "Lexdrill::CLI#perform_pull"
      - "Lexdrill::CLI#print_sheets_api_error"
      - "Lexdrill::CLI#push_after_add"
      - "Lexdrill::CLI#run_open"
      - "Lexdrill::CLI#run_wb_index"
      - "Lexdrill::CLI#run_wb_add"
      - "Lexdrill::CLI#add_workbook"
      - "Lexdrill::CLI#run_sh_index"
      - "Lexdrill::CLI#run_sh_add"
      - "Lexdrill::CLI#run_sh_remove"
      - "Lexdrill::CLI#use_sheet"
      - "Lexdrill::Workbooks#self.set_current_sheet"
      - "Lexdrill::Colorizer#self.gradient_code"
      - "Lexdrill::Inspector#self.words_summary"
      - "Lexdrill::WordList#self.next"
      - "Lexdrill::GoogleAuth#self.poll_for_token"
      - "Lexdrill::GoogleAuth#self.handle_refresh_response"
      - "Lexdrill::HTTPClient#self.build_json_request"
      - "Lexdrill::HTTPClient#self.post_form"
  TooManyConstants:
    exclude:
      - "Lexdrill::Config"
      - "Lexdrill::Beat"
      - "Lexdrill::GoogleAuth"
  DuplicateMethodCall:
    exclude:
      - "Lexdrill::CLI#run_push"
      - "Lexdrill::CLI#run_pull"
      - "Lexdrill::CLI#run_wb_add"
      - "Lexdrill::CLI#run_sh_index"
      - "Lexdrill::CLI#run_sh_add"
      - "Lexdrill::CLI#run_sh_remove"
      - "Lexdrill::CLI#use_sheet"
  FeatureEnvy:
    exclude:
      - "Lexdrill::CLI#perform_pull"
  DataClump:
    exclude:
      - "Lexdrill::CLI"
  LongParameterList:
    exclude:
      - "Lexdrill::HTTPClient#self.json_request"
      - "Lexdrill::HTTPClient#self.build_json_request"
      - "Lexdrill::SheetsClient#self.overwrite_sheet"
      - "Lexdrill::SheetsClient#self.update"
