AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0
  SuggestExtensions: false
  Exclude:
    - "bin/**/*"
    - "vendor/**/*"

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"
    - "*.gemspec"
