AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0
  SuggestExtensions: false
  Exclude:
    - "bin/**/*"
    - "vendor/**/*"

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Naming/RescuedExceptionsVariableName:
  PreferredName: error

Metrics/MethodLength:
  Max: 32
  Exclude:
    - "spec/**/*"

Metrics/ClassLength:
  Max: 365
  Exclude:
    - "spec/**/*"

Metrics/ModuleLength:
  Max: 120
  Exclude:
    - "spec/**/*"

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"
    - "*.gemspec"
